---
title: "AWS2021_22_web"
author: "Wyatt Reis"
date: '2022-05-22'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
```

```{r processing data, echo=FALSE}
# Import data with simple header
## Unburned forest hourly data before 1/10, convert to MST from UTC, filter to only include data since 11/19/2021 14:00:00
one_hour_uf_pre0110 <- read.table(
  "CR1000_7_One_Hour_0110.dat",
                                  sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = ymd_hms(TIMESTAMP), TIMESTAMP = TIMESTAMP - hours(7)) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'uf') %>%
  filter(TIMESTAMP >= "2021-11-19 07:00:00")

## N:/RStor/dmcgrath/Glacier/Cameron Peak Fire/2022 Field Season/Automated Data/Unburned/Data_220110/

## Unburned forest hourly data since 1/10, convert to MST from UTC, filter to only include data since 11/19/2021 14:00:00
one_hour_uf_post0110 <- read.table(
  "CR1000_7_One_Hour_0515.dat",
  sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = ymd_hms(TIMESTAMP), TIMESTAMP = TIMESTAMP - hours(7)) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'uf') 

## N:/RStor/dmcgrath/Glacier/Cameron Peak Fire/2022 Field Season/Automated Data/Unburned/Data_220406/

## combine unburned data into one df
one_hour_uf <- bind_rows(one_hour_uf_pre0110, one_hour_uf_post0110)

## Burned forest hourly data, convert to MST from UTC, filter to only include data since 11/19/2021 14:00:00
one_hour_bf <- read.table(
  "CR1000XSeries - new_Hourly_0515.dat",
  sep = ",", header = TRUE, skip = "1") %>%
  slice(., -(1:2)) %>%
  mutate(TIMESTAMP = ymd_hms(TIMESTAMP), TIMESTAMP = TIMESTAMP - hours(7)) %>%
  mutate_if(is.character,as.numeric) %>%
  mutate(site = 'bf')

## N:/RStor/dmcgrath/Glacier/Cameron Peak Fire/2022 Field Season/Automated Data/Burned/Data_220406/

# Combine all imported hourly data into one df
all_hr <- bind_rows(one_hour_uf, one_hour_bf) %>%
  filter(TIMESTAMP >= "2021-11-19 07:00:00")
```

```{r echo=FALSE}
## compare incoming SW between sites, put in 1 df -- HOURLY
all_rad <- all_hr %>%
    select(c(TIMESTAMP, SWin_Avg, SWout_Avg, 
           LWin_Avg, LWout_Avg,
           SWalbedo_Avg, site)) %>%
  filter(TIMESTAMP > ymd_hms("2021-11-01 00:00:00")) %>%
  mutate(yday = yday(TIMESTAMP),
         date = as_date(TIMESTAMP), hr = hour(TIMESTAMP))

## get into daily sums
all_rad_daily <- all_rad %>%
  mutate(SWalbedo_Avg = ifelse(hr >= 9 & hr <= 15, SWalbedo_Avg, NA), 
         SWalbedo_Avg = ifelse(SWalbedo_Avg < 0 | SWalbedo_Avg > 1, NA, SWalbedo_Avg)) %>%
  select(-TIMESTAMP, -hr, -yday) %>%
  group_by(date, site) %>%
  summarise(across(everything(), list(sum = sum, median = median), na.rm = TRUE)) %>%
  select(-c(SWin_Avg_median, SWout_Avg_median, LWin_Avg_median, LWout_Avg_median, SWalbedo_Avg_sum)) %>%
  #summarize_all(list(sum)) %>%
  group_by(date) %>%
  mutate(SWin_diff = lag(SWin_Avg_sum) - SWin_Avg_sum, SWin_ratio = SWin_Avg_sum/lag(SWin_Avg_sum),
         SWalbedo_ratio = SWalbedo_Avg_median/lag(SWalbedo_Avg_median)) %>%
  group_by(site) %>%
  mutate(cumSWin = cumsum(SWin_Avg_sum))
```

```{r fig.width=12,fig.height=7}

# Shortwave
sw_daily<- ggplot(all_rad_daily) +
  geom_line(aes(x = date, y= SWin_Avg_sum, color = site, linetype = "SWin")) +
  geom_line(aes(x = date, y= SWout_Avg_sum, color = site, linetype = "SWout")) +
  ggtitle("SW daily sum") +
  scale_color_manual(values = c("black", "green"))
ggplotly(sw_daily)

swin_daily_cum<- ggplot(all_rad_daily) +
  geom_line(aes(x = date, y= cumSWin, color = site)) +
  ggtitle("SWin cumulative daily sum") +
  scale_color_manual(values = c("black", "green", "blue", "yellow"))
ggplotly(swin_daily_cum)

swin_daily_ratio<- ggplot(all_rad_daily, aes(x = date, y= SWin_ratio, color = site)) +
  geom_line() +
  ggtitle("SWin daily ratio (UF/BF)") +
  scale_color_manual(values = c("black", "green"))
ggplotly(swin_daily_ratio)

swin_daily_boxplot<- ggplot(all_rad_daily, aes(x = site, y= SWin_Avg_sum)) +
  geom_boxplot() +
  ggtitle("SWin daily boxplot")
ggplotly(swin_daily_boxplot)

```

```{r fig.width=12,fig.height=7}
# Albedo
albedo_daily<- ggplot(all_rad_daily, aes(x = date, y= SWalbedo_Avg_median, color = site)) +
  geom_line() +
  ggtitle("Albedo daily median (between 0900 and 1500)")+
  scale_color_manual(values = c("black", "green"))
ggplotly(albedo_daily)

albedo_daily_ratio<- ggplot(all_rad_daily, aes(x = date, y= SWalbedo_ratio, color = site)) +
  geom_line() +
  ggtitle("Albedo daily ratio (UF/BF)")+
  scale_color_manual(values = c("black", "green"))
ggplotly(swin_daily_ratio)

albedo_daily_boxplot<- ggplot(all_rad_daily, aes(x = site, y= SWalbedo_Avg_median)) +
  geom_boxplot() +
  ggtitle("Albedo daily boxplot")+
  scale_color_manual(values = c("black", "green"))
ggplotly(albedo_daily_boxplot)

```